# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  default_python_build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # DOES NOT WORK>fix with pip install babelfish -U below
        # python-version: [3.7, 3.8, 3.9, "3.10"]
        # 3.10 failing with: AttributeError: module 'collections' has no attribute 'Callable'
        # nose problem I think.
        python-version: [3.8, 3.9, "3.10"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install .[testing]
        # pip install babelfish -U
    - name: Test with nose and doctest
      run: |
        nosetests tests
        cd ./pyquerylist
        nosetests --with-doctest *.py
        cd ..
